export default [
    { label: 'Balneário Califórnia', value: 'balneario-california' },
    { label: 'Balneário dos Golfinhos', value: 'balneario-dos-golfinhos' },
    { label: 'Barranco Alto', value: 'barranco-alto' },
    { label: 'Capricórnio I', value: 'capricornio-1' },
    { label: 'Capricórnio II', value: 'capricornio-2' },
    { label: 'Capricórnio III', value: 'capricornio-3' },
    { label: 'Caputera', value: 'caputera' },
    { label: 'Centro', value: 'centro' },
    { label: 'Cidade Jardim', value: 'cidade-jardim' },
    { label: 'Indaiá', value: 'indaia' },
    { label: 'Jardim Britânia', value: 'jardim-britania' },
    { label: 'Jardim Gaivotas', value: 'jardim-gaivotas' },
    { label: 'Jaraguazinho', value: 'jaraguazinho' },
    { label: 'Martim de Sá', value: 'martim-de-sa' },
    { label: 'Massaguaçu', value: 'massaguacu' },
    { label: 'Morro do Algodão', value: 'morro-do-algodao' },
    { label: 'Perequê-Mirim', value: 'pereque-mirim' },
    { label: 'Poiares', value: 'poiares' },
    { label: 'Porto Novo', value: 'porto-novo' },
    { label: 'Praia das Palmeiras', value: 'praia-das-palmeiras' },
    { label: 'Prainha', value: 'prainha' },
    { label: 'Sumaré', value: 'sumare' },
    { label: 'Tinga', value: 'tinga' },
    { label: 'Travessão', value: 'travessao' },
    { label: 'Vila Atlântica', value: 'vila-atlantica' },
    { label: 'Vila Ponte Seca', value: 'vila-ponte-seca' },
    { label: 'Verde Mar', value: 'verde-mar' },
];